Refactor retrying when authenticating fails during keychain resolving
- The retry logic has moved 'down the stack' to just before the keychain
attempts to access the credentials.
- only retries if the auth error was not due to invalid credentials

Co-authored-by: Dennis Leon <leonde@vmware.com>
Co-authored-by: John Ryan <jtigger@infosysengr.com>

diff --git a/test/e2e/assets/docker-credential-gcloud-race-condition-db-error b/test/e2e/assets/docker-credential-gcloud-race-condition-db-error
--- a/test/e2e/assets/docker-credential-gcloud-race-condition-db-error
+++ b/test/e2e/assets/docker-credential-gcloud-race-condition-db-error
@@ -7,7 +7,7 @@ docker volume create volume-to-use-when-locking > /dev/null
 docker run --rm -v rw:/volume-to-use-when-locking ubuntu:21.04 /bin/bash -c "$(cat <<EOF
 exec 3> /volume-to-use-when-locking/lock
 if ! flock --timeout 1 --exclusive 3; then
- echo 'ERROR: gcloud crashed (OperationalError): database is locked'
+ echo 'ERROR: gcloud crashed (OperationalError): database is locked' >&2
  exit 1
 fi
 
